packages:
  - apps/*
  - my-fantacalcio
  - packages/*
autoInstallPeers: true
minimumReleaseAge: 4320
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  supabase: true
  unrs-resolver: set this to true or false
